name: Update CP Stats

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write          # allow commits from actions

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Update stats
        run: python scripts/update_stats.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update CP stats [skip ci]" || echo "No changes"
          git push
